services:
  db:
    image: mysql
    container_name: todocli
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - java-jdbc:/var/lib/mysql

volumes:
  java-jdbc:
